### ISSUE TITLE
IDL compiler error: The "GenerateNativeProjectTask" task failed unexpectedly"

### ISSUE THREAD

**Issue by iotble** [jmmorato/openddsharp#1]
I am trying to build the HelloWorld example (x86) in Visual Studio 2017 (Win 10 OS SDK version 10.0.16299.0) and i get the below error

`1>------ Build started: Project: TestMessage, Configuration: Debug Win32 ------
1>Generating native IDL library...
1>C:\Users\test\.nuget\packages\openddsharp.idlgenerator\0.1.0\build\OpenDDSharp.IdlGenerator.targets(23,5): error MSB4018: The "GenerateNativeProjectTask" task failed unexpectedly.
1>C:\Users\test\.nuget\packages\openddsharp.idlgenerator\0.1.0\build\OpenDDSharp.IdlGenerator.targets(23,5): error MSB4018: System.Runtime.InteropServices.COMException (0x80041FE0): Exception from HRESULT: 0x80041FE0
1>C:\Users\test\.nuget\packages\openddsharp.idlgenerator\0.1.0\build\OpenDDSharp.IdlGenerator.targets(23,5): error MSB4018:    at EnvDTE.SolutionClass.AddFromTemplate(String FileName, String Destination, String ProjectName, Boolean Exclusive)
1>C:\Users\test\.nuget\packages\openddsharp.idlgenerator\0.1.0\build\OpenDDSharp.IdlGenerator.targets(23,5): error MSB4018:    at Microsoft.VisualStudio.TemplateWizard.Wizard.Execute(Object application, Int32 hwndOwner, Object[]& ContextParams, Object[]& CustomParams, wizardResult& retval)
1>C:\Users\test\.nuget\packages\openddsharp.idlgenerator\0.1.0\build\OpenDDSharp.IdlGenerator.targets(23,5): error MSB4018:    at EnvDTE80.Solution2.AddFromTemplate(String FileName, String Destination, String ProjectName, Boolean Exclusive)
1>C:\Users\test\.nuget\packages\openddsharp.idlgenerator\0.1.0\build\OpenDDSharp.IdlGenerator.targets(23,5): error MSB4018:    at OpenDDSharp.BuildTasks.GenerateNativeProjectTask.GenerateProjectFile()
1>C:\Users\test\.nuget\packages\openddsharp.idlgenerator\0.1.0\build\OpenDDSharp.IdlGenerator.targets(23,5): error MSB4018:    at OpenDDSharp.BuildTasks.GenerateNativeProjectTask.Execute()
1>C:\Users\test\.nuget\packages\openddsharp.idlgenerator\0.1.0\build\OpenDDSharp.IdlGenerator.targets(23,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Users\test\.nuget\packages\openddsharp.idlgenerator\0.1.0\build\OpenDDSharp.IdlGenerator.targets(23,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
1>Done building project "TestMessage.vcxproj" -- FAILED.
2>------ Build started: Project: HelloWorldPublisher, Configuration: Debug x86 ------
3>------ Build started: Project: HelloWorldSubscriber, Configuration: Debug x86 ------
2>CSC : error CS0006: Metadata file 'D:\test\openddsharp-master\openddsharp-master\HelloWorld\TestMessage\bin\Win32\Debug\TestMessage.dll' could not be found
3>CSC : error CS0006: Metadata file 'D:\test\openddsharp-master\openddsharp-master\HelloWorld\TestMessage\bin\Win32\Debug\TestMessage.dll' could not be found
========== Build: 0 succeeded, 3 failed, 0 up-to-date, 0 skipped ==========`

**Comment by jmmorato** [comment]
Thanks for reporting.

I can eventually reproduce your problem when restoring the nuget package the first time. After reopening the solution the issue disappeared. In any case, this problem is not new and not the only one happening in that COM object. I added some extra code to solve them but the version has not been released yet (summer arrived and not a lot of time for personal projects), I'll try to release the changes as soon as possible.

BTW, the helloworld nuget version used in the code generator project looks wrong as well. It should be 0.1.1. Anyway 0.1.1 has not significant changes on this matter.

**Comment by iotble** [comment]
Thanks for the update, I have tried by restarting the VS and as well using the latest version 0.1.1. But for me i still get the same exception. I will check the code once you have committed your fixes. 
BTW is it possible to send you a direct message.

**Comment by jmmorato** [comment]
Yes, sure. Feel free to contact me in the profile public email.

**Comment by jmmorato** [comment]
Hi,

Version 0.2.1 should fix the problems with the COM object (at least in my environment :P ). 

After pull the changes in the HelloWorld solution remember to remove the bin and obj folder in the project to start the code generation from scratch.

Happy coding!
