### ISSUE TITLE
Change all the references to Disposed Instances/Samples to Deleted Instances/Samples

### ISSUE THREAD

**Issue by jmmorato** [jmmorato/openddsharp#11]
For example:

` dataReaderQos.ReaderDataLifecycle.AutopurgeDisposedSamplesDelay`

should be:

` dataReaderQos.ReaderDataLifecycle.AutopurgeDeletedSamplesDelay`

**Comment by jmmorato** [comment]
Dispose method has an especial meaning for .Net developers when implementing [IDisposable ](https://docs.microsoft.com/en-us/dotnet/api/system.idisposable?view=netframework-4.7.2) interface. That's why, I decided (maybe wrong decision) to call it Delete instead of Dispose in the DataWriters. 

To keep the coherency in the API, it make sense to me to change all references to disposed instances/samples to delete. The other option is change back the method to Dispose as DDS standard proposes. I'm open to suggestions.

PS: Documentation is ongoing, I'll dedicate a section to main differences from the standard DDS API but really there are not too much. This one and some get_* methods that I implemented as Properties  to make the API more .Net friendly.

**Comment by mitza-oci** [comment]
I would suggest having the `Dispose` term in there, since that's what is happening in the DDS shared dataspace.  OpenDDS log messages will have it, Java or C++ apps that are interacting with this .NET app will have it, and (as we've seen) the QoS policy names reference it, etc.  Perhaps use `DisposeInstance` or `DdsDispose`?

**Comment by jmmorato** [comment]
Agree. I'll put back as Dispose. 

I was afraid because the covariant return types are not allowed in .net (as far I can remember) and as soon as a destructor is implemented in C++/CLI is considered as the IDisposable implementation in C#, therefore the compilation could fail. 
I will keep the option of `DisposeInstance` in case that I need to implement a destructor in the DataWriter.

Thanks for your advice.
