### ISSUE TITLE
AccessViolationException after issuing participant.FindTopic

### ISSUE THREAD

**Issue by MarcoRoccagli** [jmmorato/openddsharp#129]
As per title, after issuing the specified command, it successfully finds the topic, but every other operation, such read the topic name of retrieved topic produces AccessViolationException "Attempted to read or write protected memory. This is often an indication that other memory is corrupt".
Any clues on this?
Thanks

**Comment by jmmorato** [comment]
Hi,

The issue has been [reproduced](https://github.com/jmmorato/openddsharp/commit/6254a8359c7e89d12edbf76d34ac6bc14de4d177) and [fixed](https://github.com/jmmorato/openddsharp/commit/9e835ceec03c9f23564c4442741431d142c8fc88). I will create a beta version with the fix soon.

Thanks for reporting
