### ISSUE TITLE
Create "How to build" section in the Readme.md

### ISSUE THREAD

**Issue by jmmorato** [jmmorato/openddsharp#13]
Build process is tough. I created a build script in order to make it easy but even so, the script has quite a lot of requirements. I never tested the build process outside my enviroment but here a list of the requirements I can remember:

- Visual Studio 2017 installed
- Configure VSINSTALLDIR environment variable to your Visual Studio path (i.e. C:\Program Files (x86)\Microsoft Visual Studio\2017\\{_Community_|_Professional_|_Enterprise_}\\)
- .NET framework 4.6.1
- C++ support (required for the code generated)
- Windows SDK version 10.0.16299.0 (exactly that version)
- Powershell
- Git installed and in the PATH environment variable
- Perl installed and in the PATH environment variable (required to build OpenDDS)
- 7zip installed and in the PATH environment variable
- Run the script from the Build folder to ensure the path references
- Patience, the build process take looong time

To modify and compile OpenDDSharp after the build process has finished, you should add to your path the OpenDDS' lib/bin folders to the PATH environment variables. For example:
- E:\PROJECTS\OPENDDS\ext\OpenDDS\ACE_wrappers\bin_{Configuration}
- E:\PROJECTS\OPENDDS\ext\OpenDDS\bin_{Configuration}
- E:\PROJECTS\OPENDDS\ext\OpenDDS\ACE_wrappers\lib_{Configuration}
- E:\PROJECTS\OPENDDS\ext\OpenDDS\lib_{Configuration}

Test the build process in a clean machine, add missing requirements, if any, and document it in the Readme.md file.

**Comment by floatingbit** [comment]
Using VS 2017, Windows SDK version 10.0.16299.0, I cloned tag 0.2.1. Opened a developer command prompt for 2017. Ran setenv.cmd from OpenDDS-3.13. Ran the script <directory_path>\openddsharp-0.2.1\Build\build.cmd and got the following error multiple times:

<directory_path>\openddsharp-0.2.1\openddsharp\openddsharp\budgetexceededstatus.h(23): fatal error C1083: Cannot open include file: 'dds/DdsDcpsSubscriptionExtC.h': No such file or directory [<directory_path>openddsharp-0.2.1\OpenDDSharp\OpenDDSharp\OpenDDSharp.vcxproj]

**Comment by jmmorato** [comment]
You should not run the OpenDDS-3.13 setenv.cmd. The build.cmd clones and compiles OpenDDS in a specific folder "<directory_path>\ext" and it should set up all the enviroment variables pointing to that directory. I guess some enviroment variables got mixed between both scripts.

BTW, you could use a default command console, no need to use the VS developer command prompt because the build.cmd will call the correct VS script, but in case that you use a VS command prompt ensure that is not the AnyCpu one (x86_x64 I think is called).

**Comment by floatingbit** [comment]
Have you encountered the following errors before when running build.cmd from the default command console:

(1) TeamExplorer not found, but that's probably not a problem
(2) Can't find a compiler, set PATH or run this script with the --compiler option.

I have tried reinstalling VS. At the very end, I have added the list of installed packages that includes VC++. Never faced this issue with VS 2015 builds I have previously done.



What all did you install with Visual Studio 2017? The 
See output below:

openddsharp-0.2.1\Build>build.cmd
Cloning into 'OpenDDS'...
remote: Enumerating objects: 155, done.
remote: Counting objects: 100% (155/155), done.
remote: Compressing objects: 100% (79/79), done.
remote: Total 152398 (delta 63), reused 128 (delta 43), pack-reused 152243
Receiving objects: 100% (152398/152398), 61.72 MiB | 12.60 MiB/s, done.
Resolving deltas: 100% (118673/118673), done.
Checking out files: 100% (6151/6151), done.
Note: checking out 'tags/DDS-3.13'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 3eae4b29a OpenDDS Release 3.13
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[ERROR:team_explorer.bat] Directory not found : "CommonExtensions\Microsoft\TeamFoundation\Team Explorer"
[ERROR:VsDevCmd.bat] *** VsDevCmd.bat encountered errors. Environment may be incomplete and/or incorrect. ***
[ERROR:VsDevCmd.bat] In an uninitialized command prompt, please 'set VSCMD_DEBUG=[value]' and then re-run
[ERROR:VsDevCmd.bat] vsdevcmd.bat [args] for additional details.
[ERROR:VsDevCmd.bat] Where [value] is:
[ERROR:VsDevCmd.bat]    1 : basic debug logging
[ERROR:VsDevCmd.bat]    2 : detailed debug logging
[ERROR:VsDevCmd.bat]    3 : trace level logging. Redirection of output to a file when using this level is recommended.
[ERROR:VsDevCmd.bat] Example: set VSCMD_DEBUG=3
[ERROR:VsDevCmd.bat]          vsdevcmd.bat > vsdevcmd.trace.txt 2>&1

7-Zip 18.05 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-04-30

Scanning the drive for archives:
1 file, 58655607 bytes (56 MiB)

Extracting archive: ACE+TAO-2.2a_with_latest_patches_NO_makefiles.zip
--
Path = ACE+TAO-2.2a_with_latest_patches_NO_makefiles.zip
Type = zip
Physical Size = 58655607

Everything is Ok

Folders: 2561
Files: 23235
Size:       168753857
Compressed: 58655607
ERROR: Can't find a compiler, set PATH or run this script with the --compiler option.
  For Microsoft Visual C++, run this script from the Visual Studio Command Prompt.
Stopped at configure line 382.



#######################################
List of Visual Studio packages:

Microsoft Visual Studio Professional 2017 
Version 15.8.8
VisualStudio.15.Release/15.8.8+28010.2048
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Professional

Visual C++ 2017   00369-60000-00001-AA939
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.13.10627.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.8.05085.0
ASP.NET and Web Tools 2017

C# Tools   2.9.0-beta8-63208-01
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   15.8.20822.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.9.0-beta8-63208-01
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Universal Windows Apps   15.0.28010.2046
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.
#################################

**Comment by floatingbit** [comment]
Thanks!

Looked into the vsdevcmd.trace.txt and found the problem. There was a \ missing in the path to the VSINSTALLDIR that should be "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\" in place of "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise" - you might want to update that in the build documentation.

Secondly, there was a problem that I had faced while configuring OpenDDS-3.13 that mitza-oci had helped me resolve here https://github.com/objectcomputing/OpenDDS/issues/945 using the commit tag https://github.com/objectcomputing/OpenDDS/commit/e03928265bd67674b370202963c32d73381c55f4 wherein I was getting the error: "ERROR: Could not detect Visual C++ version, try running this script from the Visual Studio Command Prompt."

I used that updated configure script and was able to build the solution until I got the following error:

GenerateNativeProjectTarget:
  Generating native IDL library...
  TemplatePath: C:\Users\dghosh\Development\Playground\openddsharp-0.2.1\OpenDDSharp\OpenDDSharp.IdlGenerator\NativeIdlProjectTemplate.vstemplate
  IntDir: C:\Users\dghosh\Development\Playground\openddsharp-0.2.1\OpenDDSharp\TestIdl\obj\x64\Debug\
  _projectName: TestIdlNative.vcxproj
  Exception: System.Runtime.InteropServices.COMException (0x8001010A): The message filter indicated that the application is busy. (Exception from HRESULT: 0x8001010A (RPC_E_SERVERCALL_RETRYLATER))
     at EnvDTE100.Solution4.get_Projects()
     at OpenDDSharp.BuildTasks.GenerateNativeProjectTask.AddProjectTemplate() in C:\Users\dghosh\Development\Playground\openddsharp-0.2.1\OpenDDSharp\OpenDDSharp.BuildTasks\GenerateNativeProjectTask.cs:line 214

And the build seems to have stopped/frozen there.

**Comment by PierrePontic** [comment]
I just tried the procedure described here "http://www.openddsharp.com/Documentation/GetStarted", and I can't get it working. I get an error "OpenDDSharp.IdlGenerator.targets(23,32): error MSB4184:"
because of the lines

<Target Name="GenerateNativeProjectTarget" BeforeTargets="PreBuildEvent">
    <GenerateNativeProjectTask IntDir="$([System.IO.Path]::GetFullPath('$(IntDir)'))" OriginalProjectName="$(ProjectName)" IdlFiles="@(IdlFiles)" TemplatePath="$(MSBuildThisFileDirectory)..\tools\native_project_tempate\NativeIdlProjectTemplate.vstemplate" Configuration="$(Configuration)" Platform="$(Platform)" />
  </Target>


because the variable $(IntDir) is empty. I launched devenv from the developper command prompt for VS2019, after a call to the setenv.cmd in my OpenDDS forlder.

Did I missed something ?

**Comment by jmmorato** [comment]
The SDK should be installed from the Visual Studio Installer:

![image](https://user-images.githubusercontent.com/1584509/102502768-4ce48100-407f-11eb-9ce1-ea631887e934.png)

You should have installed the Desktop development for C++ and C++/CLI as well.


PS: Your question is offtopic with the current discussion in this thread, please open different tickets to ask for support.

**Comment by jmmorato** [comment]
Added How to build section based on Cake Script #43
