### ISSUE TITLE
Memory leak in the Write method when using sequences

### ISSUE THREAD

**Issue by chiuras** [jmmorato/openddsharp#14]
When I use sequences in IDL like follow:
module DDSMessage
{
#pragma DCPS_DATA_TYPE "DDSMessage::DDSMessage"

	typedef sequence<octet> DDSContext;
	struct DDSMessage
	{
		long byteArrayLength;
		DDSContext   byteArray;
	};
};
I found when I write sample in publisher, there is memory leak.
Attached you can see my example.
Thanks!
[Program - publisher.txt](https://github.com/jmmorato/openddsharp/files/2965442/Program.-.publisher.txt)
[Program - subscriber.txt](https://github.com/jmmorato/openddsharp/files/2965445/Program.-.subscriber.txt)
[DDSMessage.idl.txt](https://github.com/jmmorato/openddsharp/files/2965448/DDSMessage.idl.txt)

**Comment by jmmorato** [comment]
Yep, that looks as a memory leak.

The problem has been fixed and will be released on the next version. For the moment, as a workaround, you can use the idl generator version that I have generated with the fix:

[openddsharp_idl.zip](https://github.com/jmmorato/openddsharp/files/2967285/openddsharp_idl.zip)

You need to drop the openddsharp_id.exe in the `.nuget\packages\openddsharp.idlgenerator\0.3.0\tools` folder.

Let me know if that works for you and thanks for reporting.

**Comment by chiuras** [comment]
It works. Thanks a lot!
