### ISSUE TITLE
Incorrect documentation showing mapping in IDL data type translations

### ISSUE THREAD

**Issue by iisfaq** [jmmorato/openddsharp#145]
On the following page https://www.openddsharp.com/articles/idl.html there are some issues.

I created the following attributes with the data types in my IDL file which generated the following data types

        short			c;
        int16			d;
        unsigned short		e;
        uint16			f;
        long			g;
        int32			h;
        unsigned long		i;
        uint32			j;
        long long			k;
        int64			l;
        unsigned long long		m;
        uint64 			n;

I generated each data type and found the following

IDL Type | C# per docs | c# Actual
-- | -- | --
int8 | not supported | not supported
uint8 | not supported | not supported
short | short | Int16
int16 | short | Int16
unsigned short | ushort | UInt16
uint16 | ushort | UInt16
long | int | Int32
int32 | int | Int32
unsigned long | ushort | ❌UInt32
uint32 | ushort | ❌UInt32
long long | int | ❌Int64
int64 | int | ❌Int64
unsigned long long | ushort | ❌UInt64
uint64 | ushort | ❌UInt64

I thought some of these do not make sense.

**Comment by jmmorato** [comment]
Oops... you are right, generation is ok but documentation is wrong. I will fix it soon, thanks for reporting.

**Comment by jmmorato** [comment]
Corrected and published: https://www.openddsharp.com/articles/idl.html
