### ISSUE TITLE
Errors in the getting started doc and issues building the getting started applications

### ISSUE THREAD

**Issue by mellegge** [jmmorato/openddsharp#167]
Trying to work through the document at https://www.openddsharp.com/articles/getting_started.html
First some documentations errors:
1) Implemented runtime identifier win-64 should be win-x64
2) "dotnet build HelloPublisher.csproj" should be "dotnet build Publisher.csproj" I believe since that is the project created above in the turorial
3) "dotnet build HelloSubscriber.csproj" should be "dotnet build Subsriber.csproj" I believe since that is the project created above in the turorial

Build issues:
1) TestMessage builds with no errors but Publisher does not build.  It complains about "TestMessageWrapper.dll" not being found.  Sure enough when I check the outputs of TestMessage, this dll does not exist.  Note I tried building Publisher in Release but it seems TestMessage defaults to Debug?   Trying to build TestMessage with the --configuration Release --runtime win-x64 fails due to TestMessageWrapper.dll not being found in the obj directory

**Comment by jmmorato** [comment]
If you already tried with the wrong documented runtime identifier, clean the project first (dotnet clean) and/or remove `obj` and `bin` folders of all projects.

It that does not work, please share here the build log.

About, documentation issues... I think I already fixed before, perhaps some merge problems revert it back. Thanks to point them.

**Comment by mellegge** [comment]
Using the dot clean got me further.  However now I get an error in the Publisher program "The type or namespace name "MessageTypeSupport" could not be found (are you missing a directive or assembly reference?)"

I followed the "dotnet add Publisher/Publisher.csproj reference TestMessage/TestMessage.csproj" step.  Seems there is another missing step maybe?

**Comment by jmmorato** [comment]
For sure is required, same as for the subscriber project... and not documented.
I will include it as well.

**Comment by mellegge** [comment]
I followed those steps.  Still seem to be missing something

**Comment by jmmorato** [comment]
Could you share your projects in a zip files?

**Comment by mellegge** [comment]
Got it working.  I had to open both the Subscriber and Publisher projects in VS (2022) and remove the TestMessage project from the dependencies.  Then from within VS I added the TestMessage.dll.  From there I could add "using HelloWorld;"  Solved my compile problem.

Interesting to note is that I had to copy the TestMessageWrapper.dll manually into the Subscriber and Publisher output directories in order for the Publisher and Subscriber to run.

One more doc error: 
List<SampleInfo> receivedInfo = new Lis<SampleInfo>();  //Lis should be List

Thanks for your help

**Comment by jmmorato** [comment]
If you add the dll reference directly the copy of the native `TestMessageWrapper.dll` must be copied manually as you mentioned. 

The automatic copy is done by the `ProjectReference` but not in a direct dll reference. I will review the article and fix the already mentioned doc issues and the missing step for the reference.

**Comment by jmmorato** [comment]
Documentation has been fixed and published.

Thanks for reporting!
