### ISSUE TITLE
@key vs #pragma DCPS_DATA_KEY and the documentation

### ISSUE THREAD

**Issue by jspg** [jmmorato/openddsharp#176]
Hello, 
Looking at the documentation regarding IDL here: https://www.openddsharp.com/articles/idl.html shows that support for `@key` is not implemented.
However, looking at the generated code (using version 0.8.23023.106 of the NuGet package) it seems that `#pragma DCPS_DATA_KEY "<namespace>::<struct name> <field name>"` generates the same code as omitting it completely.
In fact, it seems that `@key` is the one that generates different code from not having key or pragma.
Is the documentation just not updated and we can expect `@key` to behave according to the specification?

**Comment by jmmorato** [comment]
Yes, documentation is outdated. `@key` is the correct way to declare a key field and `@topic` to ensure the `TypeSupport` and `DataWriter/Reader` classes are generated for the structure.

I will update the documentation and close this ticket when published.

Thanks for reporting!

**Comment by jspg** [comment]
Thank you for the quick reply!

**Comment by jmmorato** [comment]
Documentation updated and published.
