### ISSUE TITLE
Using Instances 

### ISSUE THREAD

**Issue by bbetulbayram** [jmmorato/openddsharp#19]
Hello, 
I am trying to using instances with samples but I am not certain whether to use TakeNextInstance or TakeNextSample. TakeNextIntance method take an InstanceHandle parameter but where do we get these handle? if from topic, as I observed; topic.InstanceHandle returns only one InstanceHandle, if we have more than one Instance then how do we separete these Instances?

**Comment by jmmorato** [comment]
The parameter instance handle of `TakeNextInstance` indicates the previous handle of the one you want to 'take'.

For example:
``` csharp
InstanceHandle previous = InstanceHandle.HandleNil;
while (dr.TakeNextInstance(samples, infos, previous) == ReturnCode.Ok)
{
    previous = infos[0].InstanceHandle;
    for (int i = 0; i < samples.Count; i++)
    {
          // Process your samples
    }
}
```

The first call with the `InstanceHandle.HandleNil` value will return the first instance found in the queue. That parameter is more important when using `read_next_instance` but for `take_next_instance`, as it removes all the samples of the instances from the queue, you could even call it always with `InstanceHandle.HandleNil` and takes always the first instance in the queue until the queue is empty.

On the other hand, `TakeNextSample` will take the first sample found on the data reader queue, without checking the instance that the sample belongs.

If you want to take all the samples of an specific instance you could do:

``` csharp
InstanceHandle handle = dr.LookupInstance(new TestStruct
{
     Id = 1 // Id is the key field
});

if (handle != InstanceHandle.HandleNil)
{
    dr.TakeInstance(samples, infos, handle);
}
```

**Comment by bbetulbayram** [comment]
I'm just trying to count how many messages I got from an Instance and when I apply this It can not go through  "if (handle != InstanceHandle.HandleNil)" line. When I comment out this "if", I see that result is BadParameter. 
```
MessageDataReader messageReader = new MessageDataReader(reader);
            List<OpenDDSharp.InstanceMessage.Message> receivedData = new List<OpenDDSharp.InstanceMessage.Message>();
            List<SampleInfo> receivedInfo = new List<SampleInfo>();
            StatusMask mask ;
            Totalcount = 0;
            InstanceHandle handle = messageReader.LookupInstance(new OpenDDSharp.InstanceMessage.Message
            {
                ID = "1" // Id is the key field
            });
            count = 0;

            while (IsRadioActive == true)
            {
                
                    mask = messageReader.StatusChanges;
                    if ((mask & StatusKind.DataAvailableStatus) != 0)
                    {
                       if (handle != InstanceHandle.HandleNil)
                        {
                            result = messageReader.TakeInstance(receivedData, receivedInfo, handle);
                            if (result == ReturnCode.Ok)
                            {
                                count++;
                           }
                      }
                 }
```

**Comment by jmmorato** [comment]
If you could provide your project would be easier to understand what is happening. If it is not possible to you to share the code, I'll try an example to simulate your use case when I have some time.

**Comment by bbetulbayram** [comment]
Sure, I  attached the subscriber project file because it is a winForms application
[SubscriberWinForm.zip](https://github.com/jmmorato/openddsharp/files/3583724/SubscriberWinForm.zip)
. The Publisher side takes an argument of the message structure's key from cmd and send samples of that instance. Subscriber side tries taking that instances and counts the total messages. I am executing 10 publishers with 1 to 10 as an argument. At the subscriber side, to start receiving messages; just check start receiving messages checkbox and when publisher stops sending messages hit the end all button. zeroise button refresh the app. I know it is a dummy design, I use it to test OpenDDSharp after my work time so sorry about that. Thank you for your help, I appreciate it.

the IDL file: 
```
module InstanceMessage
{

#pragma DCPS_DATA_TYPE "InstanceMessage::Message"
#pragma DCPS_DATA_KEY "InstanceMessage::Message ID"

   struct Message
   {
	/** User ID */
	string ID;
	/**  text */
	string messsage;
	
 };
};
```
the Publisher program.cs

```
using System;
using OpenDDSharp.DDS;
using OpenDDSharp.InstanceMessage;
using OpenDDSharp.OpenDDS.DCPS;
using System.Threading;
using System.Diagnostics;

namespace OpenDDSharp.HelloWorldPublisher
{
    class Program
    {
        static void Main(string[] args)
        {
            if (args.Length == 0)
            {
                System.Console.WriteLine("Please enter a numeric argument.");
                throw new Exception("Please enter a numeric argument");
            }

            Ace.Init();

            DomainParticipantFactory dpf = ParticipantService.Instance.GetDomainParticipantFactory("-DCPSConfigFile", "rtps.ini");
            DomainParticipant participant = dpf.CreateParticipant(42);
            if (participant == null)
            {
                throw new Exception("Could not create the participant");
            }

            MessageTypeSupport support = new MessageTypeSupport();
            ReturnCode result = support.RegisterType(participant, support.GetTypeName());
            if (result != ReturnCode.Ok)
            {
                throw new Exception("Could not register type: " + result.ToString());
            }

            Topic topic = participant.CreateTopic("MessageTopic", support.GetTypeName());
            if (topic == null)
            {
                throw new Exception("Could not create the message topic");
            }

            Publisher publisher = participant.CreatePublisher();
            if (publisher == null)
            {
                throw new Exception("Could not create the publisher");
            }

            DataWriter writer = publisher.CreateDataWriter(topic);
            if (writer == null)
            {
                throw new Exception("Could not create the data writer");
            }
            MessageDataWriter messageWriter = new MessageDataWriter(writer);
            Console.WriteLine("Waiting for a subscriber...");
            PublicationMatchedStatus status = new PublicationMatchedStatus();
            do
            {
                result = messageWriter.GetPublicationMatchedStatus(ref status);
                System.Threading.Thread.Sleep(500);
            }
            while (status.CurrentCount < 1);

            int count = 0;
            Console.WriteLine("Subscriber found, writting data....");
            string message = args[0] + " Says: ";

            Stopwatch stopwatch = new Stopwatch();
            TimeSpan timeGone = new TimeSpan(0,0,0,0);
            TimeSpan RequiredTimeLine = new TimeSpan(0, 0, 1, 0, 0);//set to 1 mins
            ReturnCode ret;
            //send messages through time period
            while (timeGone.Minutes < RequiredTimeLine.Minutes)
            {
                stopwatch.Start();
                ret = messageWriter.Write(new Message
                {
                    ID = args[0],
                    messsage = message + count.ToString()
                });
                if(ret == ReturnCode.Ok)
                    count++;
                Console.WriteLine(count.ToString());
                Thread.Sleep(50);
                timeGone = stopwatch.Elapsed;
            }
            stopwatch.Stop();
            participant.DeleteContainedEntities();
            dpf.DeleteParticipant(participant);
            ParticipantService.Instance.Shutdown();

            Ace.Fini();
        }
    }
}
```

**Comment by jmmorato** [comment]
hey @bbetulbayram 

Your code is almost correct. 

For your use case `TakeNextInstance` is not correct, you should use `TakeInstance` with the correct instance handle.

The `if (handle != InstanceHandle.HandleNil)` line is good to keep it. The method `LookupInstance` returns InstanceHandle.HandleNil if the instance is not registered (not sample received yet or the instance has been unregistered by the writer). Therefore, better to keep the check and try to lookup the instance handle on each loop.

Take a look to the modifications I did in your project and let me know if makes sense for you.

PS: Why do you use the `string ID;` and parse the value to integer
 in code? You could directly define the field as integer by changing the IDL to `long ID;`

[SolutionFolder.zip](https://github.com/jmmorato/openddsharp/files/3586890/SolutionFolder.zip)

**Comment by bbetulbayram** [comment]
Hello @jmmorato 

Sorry for the late reply. I did try your modifications and it worked like a magic. There are 2 messages lost in 115284 messages in 10 mins this way, better than I achieved. I guess I used wrong the TakeInstances method earlier. 

For your "string ID" question, either I would parse string to int at Publisher side as it takes arguments as string or at Subscriber side to achieve ID. I firstly tried send messages without checking instances and used the same Publisher code with this example so I did not change IDL side nor Publisher side.

Thank you for your time and attention.

**Comment by jmmorato** [comment]
Great!

BTW, a much better implementation, if you know the total number of instances to monitor, could be implemented using content filtering topics.

About the the lost messages, I think the default value for the datareaders RELIABILITY QoS is BestEffort, try to change it to RELIABLE.
