### ISSUE TITLE
[Request] Update Project Template

### ISSUE THREAD

**Issue by ghostidentity** [jmmorato/openddsharp#204]
Hello guys,

Can you update the project template , where it shows the interaction between publisher and subscriber ?

![image](https://github.com/jmmorato/openddsharp/assets/4637625/0f05b77c-9032-4415-98ed-e315b9e52688)

**Comment by ghostidentity** [comment]
also typo: 
![image](https://github.com/jmmorato/openddsharp/assets/4637625/8735aab0-d342-4a59-bc0f-b524b1c2a171)

**Comment by ghostidentity** [comment]
Also, can we have a tooling support, where it will fix the issue "SetEnvVar" by adding xml declaration on where to find the IDL ? 
![image](https://github.com/jmmorato/openddsharp/assets/4637625/a7c79e6c-0b85-4010-9af5-2526460cf3b5)

**Comment by ghostidentity** [comment]
The getting started guide does not mentioned on how to obtain the MessageDataWriter ?  
![image](https://github.com/jmmorato/openddsharp/assets/4637625/a8f01bf4-993c-4f9b-af6b-109de86a24c4)

**Comment by ghostidentity** [comment]
I noticed there's a repo: https://github.com/jmmorato/openddsharp_standard_helloworld, but I could not build the whole project .  
![image](https://github.com/jmmorato/openddsharp/assets/4637625/c7092534-e76d-4d3e-8d6c-a68065b239e5)

**Comment by ghostidentity** [comment]
Thanks, but the recent PR does not build also. 
![image](https://github.com/jmmorato/openddsharp/assets/4637625/e1eab9da-c958-427d-8a0e-95023cf386fc)

**Comment by jmmorato** [comment]
Please, remove the bin and obj folders and Rebuild the application

**Comment by ghostidentity** [comment]
done. i deleted both bin and obj folders,  but it cant build the project.

**Comment by jmmorato** [comment]
Could you share the full build log?

**Comment by mtagab008** [comment]
I'm not sure where to find the full build log, but here's the output. 

Rebuild started...
1>------ Rebuild All started: Project: TestMessage, Configuration: Debug x64 ------
Restored G:\mtagab\net\openddsharp_standard_helloworld\TestMessage\TestMessage.csproj (in 413 ms).
Restored G:\mtagab\net\openddsharp_standard_helloworld\HelloWorldPublisher\HelloWorldPublisher.csproj (in 413 ms).
Restored G:\mtagab\net\openddsharp_standard_helloworld\HelloWorldSubscriber\HelloWorldSubscriber.csproj (in 413 ms).
1>Cleaning TestMessage.idl auto-generated files...
1>Set OpenDDS environment variables:
1>DDS_ROOT=
1>ACE_ROOT=
1>TAO_ROOT=
1>RAPIDJSON_ROOT=
1>C:\Users\mtaga\.nuget\packages\openddsharp.idlgenerator\3.250.2-beta20065\build\OpenDDSharp.IdlGenerator.targets(113,2): error MSB4044: The "SetEnvVar" task was not given a value for the required parameter "Value".
1>Done building project "TestMessage.csproj" -- FAILED.
2>------ Rebuild All started: Project: HelloWorldSubscriber, Configuration: Debug x64 ------
3>------ Rebuild All started: Project: HelloWorldPublisher, Configuration: Debug x64 ------
3>CSC : error CS0006: Metadata file 'G:\mtagab\net\openddsharp_standard_helloworld\TestMessage\obj\x64\Debug\net6.0\ref\TestMessage.dll' could not be found
3>Done building project "HelloWorldPublisher.csproj" -- FAILED.
2>CSC : error CS0006: Metadata file 'G:\mtagab\net\openddsharp_standard_helloworld\TestMessage\obj\x64\Debug\net6.0\ref\TestMessage.dll' could not be found
2>Done building project "HelloWorldSubscriber.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 3 failed, 0 skipped ==========
========== Rebuild started at 6:08 PM and took 00.869 seconds ==========

**Comment by jmmorato** [comment]
Add `<RuntimeIdentifier>win-x64</RuntimeIdentifier>` to the `TestMessage.csproj` after the `<RuntimeIdentifiers>` tag.

I will fix the template in a next PR.

**Comment by mtagab008** [comment]
> Add `<RuntimeIdentifier>win-x64</RuntimeIdentifier>` to the `TestMessage.csproj` after the `<RuntimeIdentifiers>` tag.
> 
> I will fix the template in a next PR.

It resolved the SetEnvVar issue, but it introduce another issue.  
![image](https://github.com/jmmorato/openddsharp/assets/83455172/fc7e64f0-4465-48a1-b79b-c9875b112aca)

**Comment by jmmorato** [comment]
Build output pls

**Comment by jmmorato** [comment]
Seems that you have not `cmake` installed in your system (or not in your path). 
https://www.openddsharp.com/articles/getting_started.html#requirements

**Comment by ghostidentity** [comment]
thank you, the errors are now resolved and I'm able to confirm that the publisher and subscriber solution are working.

**Comment by jmmorato** [comment]
Fix released in latest version 3.250.2
