### ISSUE TITLE
Implementing DataReaders/DataWriters using Generics

### ISSUE THREAD

**Issue by ethanshattuck** [jmmorato/openddsharp#21]
I was able to abstract the process of creating Specific DataReaders/DataWriters using reflection in C#. In OpenDDS, I was able to achieve a similar solution using templated classes to create and return specific data readers and writers. Pleased with the performance of the templated class technique in C++, I was wondering if it is possible to achieve the same functionality in C# using Generic classes. The issue I run into occurs when I try to call a generic type's function. (Example: Calling typesupport.RegisterType; C# cannot interpret the generic type or its functions at runtime). This could be solved if the type supports could inherit interfaces during their code generation. Is this currently possible? Is there a way to edit the code generation of certain classes?

Thanks

**Comment by jmmorato** [comment]
Hi @ethanshattuck 

In the OpenDDSharp.IdlGenerator nuget package you can find the template files for the TypeSupport, DataReader and DataWriter classes .

%userprofile%\.nuget\packages\openddsharp.idlgenerator\0.4.1\tools\DDS\dds\idl

The `HeaderTemplate.txt` and `ImplTemplate.txt` are the ones used by OpenDDSharp (C++/CLI). The `IDLTemplate.txt` is the one used by OpenDDS.

Just modifying the `HeaderTemplate.txt` should be enough to solve your situation.
