### ISSUE TITLE
Openddsharp.native nuget package flagged as Malicious by MaxSecure in VirusTotal Scan

### ISSUE THREAD

**Issue by khtraveltwo** [jmmorato/openddsharp#227]
Hello. I submitted openddsharp.native.3.250.2.nupkg to VirusTotal for a scan and 1/59 Security vendors, MaxSecure flagged this file as malicious Tojan.Malware.300983.susgen. However, I suspect it is a false positive. May I check if you have encountered this issue before? Thanks!

https://www.virustotal.com/gui/file/875259b9d9488b8eef556caa4e02b4b33f98d2407872112ada1d543e9cc13014/detection

![VirusTotalScan](https://github.com/jmmorato/openddsharp/assets/102568573/e8dc2f14-9fbc-48b6-bec1-dfa4d28b4050)

**Comment by jmmorato** [comment]
I never performed the test, thanks for that.

It is a false positive, all other 58 scans are green. MaxSecure has not a good reputation as antivirus, if you take a look to google results you will see several posts marking them as just scam.

In any case, all the code used in OpenDDSharp is open source, so feel free to check yourself 😉

**Comment by khtraveltwo** [comment]
Noted and thanks so much for your response!
