### ISSUE TITLE
Question: Reader reads disposed topics?

### ISSUE THREAD

**Issue by mellegge** [jmmorato/openddsharp#232]
We have two applications - one has a writer , the other a reader.  The writer publishes several instances of a topic and the reader gets these topics as expected.  All good.  The application with the writer shuts down and the reader gets a burst of topics almost within the same timeframe (milliseconds apart).  These topics all have valid keys but the data is blank.

1) Are these topics the result of some cleanup by the reader when it detects the writer has gone away?
2) How do we prevent the reader from consuming these topics? (I can chose to not process topics with blank fields in my code, but wondering how to do this from the OpenDDS perspective)

TIA
Mel

**Comment by mellegge** [comment]
Solved:
1) The reader sends topics with "NotAliveWritersInstanceState";
2) I updated our reader to not process topics in this state

**Comment by jmmorato** [comment]
Yep, that's the normal behaviour of the DDS instances
