### ISSUE TITLE
Failure on the "export_file_generator.exe" line in the IDL code generator

### ISSUE THREAD

**Issue by Cingulara** [jmmorato/openddsharp#26]
I am running through the IDL generator with the Test.idl file and all goes well up to the line in the generated vcxproj file near the bottom that references "export_file_generator.exe". My OpenDDS does not have that exe anywhere in it. Is there an option to set on compiling OpenDDS to generate that? is that done some other way? 

I have Windows 10, VS 2019, and the proper Windows SDK installed. OpenDDS compiled fine for all other items. I am just missing this file.

**Comment by Cingulara** [comment]
Ahh I missed using the build cmd script.  I just built using the solution
file.  My mistake.  I will try that Right now.  I was hoping I did
something wrong.

Thank you.
-- 
Dale Bingham
CTO and Chief Technology Evangelist
Cingulara
https://www.cingulara.com
410-984-0001

**Comment by jmmorato** [comment]
BTW,
> I have Windows 10, VS 2019, and the proper Windows SDK installed.

VS 2019 is not yet supported to build OpenDDSharp. Some modifications are needed in OpenDDS and OpenDDSharp to make it work. We are working on that and soon will be merged to the master branch.

Regards

**Comment by jmmorato** [comment]
I new `AfterBuild` task has been added in order to copy the output of the `ExportFileGenerator` project to the corresponding `%ACE_ROOT%\bin` folder.
