### ISSUE TITLE
GetStarted procedure fail.

### ISSUE THREAD

**Issue by PierrePontic** [jmmorato/openddsharp#29]
I just tried the procedure described here "http://www.openddsharp.com/Documentation/GetStarted", and I can't get it working. I get an error "OpenDDSharp.IdlGenerator.targets(23,32): error MSB4184:"
because of the following lines:
`
<Target Name="GenerateNativeProjectTarget" BeforeTargets="PreBuildEvent">
  <GenerateNativeProjectTask IntDir="$([System.IO.Path]::GetFullPath('$(IntDir)'))" OriginalProjectName="$(ProjectName)" IdlFiles="@(IdlFiles)" TemplatePath="$(MSBuildThisFileDirectory)..\tools\native_project_tempate\NativeIdlProjectTemplate.vstemplate" Configuration="$(Configuration)" Platform="$(Platform)" />
</Target>
`

because the variable $(IntDir) is empty. As far as I know, the $(IntDir) is set to a folder for temporary files (set to ".\obj\$(Platform)\$(Configuration)\" in my configuration)

Moreover, if I browse the properties of the project, some variables are using the variable $(IntDir), and the variable is not empty : ".\obj\Win32\Release\" in my case.

Did I missed a detail about that variable ?

**Comment by jmmorato** [comment]
Could you attach your projects so I can take a look in my dev machine?

**Comment by PierrePontic** [comment]
Here it is. I'm using Microsoft Visual Studio Professional 2019, Version 16.8.3
[testSSI.zip](https://github.com/jmmorato/openddsharp/files/5725057/testSSI.zip)

**Comment by jmmorato** [comment]
You added the OpenDDSharp.IdlGenerator NuGet package in your TestSSL C# main project.
The IdlGenerator package must be only added to the IDL C++/CLI projects, that's why the IntDir variable is undefined, that variable has different name in C# projects.

Just remove the OpenDDSharp.IdlGenerator from the testSSL project and rebuild again the solution.

**Comment by PierrePontic** [comment]
Ok, your idea solve my problem,

BUT.

If I do not use OpenDDSharp.IdlGenerator NuGet package, there is no OpenDDS namespace available. The simple "OpenDDSharp" nuget package do not add any reference. Whatever the nuget package I use the types "MessageDataWriter" and "MessageTypeSupport" keep being undefined.


Could you join a building/working solution ? (the solution provided in your git repository do not build as it ask for the nuget package OpenDDSharp 0.5.1, that is not available)

**Comment by jmmorato** [comment]
> The simple "OpenDDSharp" nuget package do not add any reference.

It adds the reference to the OpenDDSharp API, and during the build, it copies the native OpenDDS libraries.

> Whatever the nuget package I use the types "MessageDataWriter" and "MessageTypeSupport" keep being undefined.

You are right, the example is outdated. The IDL syntax changed for latest versions of OpendDDS and now should be used IDL v4.0:

```
module HelloWorld{
    @topic
    struct Message {
        string Content;
    };
};
```
I will update the example before closing this ticket.

> the solution provided in your git repository do not build as it ask for the nuget package OpenDDSharp 0.5.1, that is not available.

Version 0.5.1 has not been released yet. If you want to build the example, please pull the tag `v0.5.0` from the master branch.

Attached my modifications to your project: [testSSI_modified.zip](https://github.com/jmmorato/openddsharp/files/5753363/testSSI_modified.zip)

**Comment by PierrePontic** [comment]
Ok, I built the example in the v0.5.0 Tag, it worked fine.
I still do not understand how it can build without having OpenDDSharp in each project references. But I will study this example.

Thank you for your help.
