### ISSUE TITLE
IDL interpretation fail (with MIDL2025 error ?)

### ISSUE THREAD

**Issue by PierrePontic** [jmmorato/openddsharp#30]
Hello, while using this .idl file,
```
module toto
{
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

/**
    * Represents a point in a 2D geometric space, with integer values.
    */
struct SPointI
{
    long x;
    long y;
};
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

/**
 * Represents a line in a 2D geometric space, with integer values.
 */
struct SLineI
{
    SPointI pointA; /**< first point of the line */
    SPointI pointB; /**< second point of the line */
};
};
```

I get the following error in the build output : 
```
1>Generating native IDL library...
1>Generating SSI.idl code...
1>tao-idli_AOzGeA.cpp
1>Processing idl\Geometry.idl
1>Geometry.idl
1>idl\Geometry.idl(24): error MIDL2025: syntax error : expecting a type specification near "SPointI"
1>idl\Geometry.idl(25): error MIDL2026: cannot recover from earlier syntax errors; aborting compilation
1>Génération du projet "SSI.vcxproj" terminée -- ÉCHEC.
```

I don't get why it's parsed by midl (the Microsoft idl parser) instead of openddsharp_idl.
moreover, if I include other idl files, it works fine. 

I tried to rename the file, it do not works better.

**Comment by jmmorato** [comment]
I guess you dropped the IDL file directly in the project, the default action on Visual C++ projects is to compile with MIDL:
![image](https://user-images.githubusercontent.com/1584509/104878355-10e15c00-595c-11eb-83a1-808815b99f42.png)

You can change it to `None` manually but my advice is to remove the file and always add IDLs with the `Add New Item -> OpenDDSharp IDL Item`:

![image](https://user-images.githubusercontent.com/1584509/104878528-6c134e80-595c-11eb-85e0-51a1e61f4350.png)

**Comment by PierrePontic** [comment]
Nice guess !
Thank you ! 

(As I have multiple existing files to add, it is simpler to edit the vcxproj file)
