### ISSUE TITLE
.Net Framework 4.5 can't find OpenDDSharp Nuget

### ISSUE THREAD

**Issue by PierrePontic** [jmmorato/openddsharp#31]
If a project is made for .Net Framework 4.7.2 it works fine with OpenDDSharp, but if I change the framework version of the project (to 4.5) it do not work anymore.

If I create a project for .Net Framework 4.5, and try to append the Nuget OpenDDSharp, it tell me that it can't find the nuget for framework 4.5 ... 

Is there a workaround ? (I mean something else than rebuild the package for net4.5, because I'm still not able to build it)

**Comment by jmmorato** [comment]
I'm afraid not, the only workaround is to build against .NET Framework 4.5 and perhaps that will require some code adaptations...

I'm working in a new build system based on Cake that will make easier to build and modify the project, for the moment if you need help start reading the discussion here: https://github.com/jmmorato/openddsharp/issues/13 and feel free to ask for support
