### ISSUE TITLE
GetDomainParticipantFactory returning null

### ISSUE THREAD

**Issue by ww1965** [jmmorato/openddsharp#35]
I am trying to create a simple application based on the HelloWorld example.  Every time I call ParticipantService.Instance.GetDomainParticipantFactory, I get a null value returned.

Sample code attached.
[TestApplication.zip](https://github.com/jmmorato/openddsharp/files/5977917/TestApplication.zip)

**Comment by jmmorato** [comment]
If I call the factory with debug parameters:
```csharp
ParticipantService.Instance.GetDomainParticipantFactory("-DCPSConfigFile", "rtps.ini", "-DCPSDebugLevel", "10", "-ORBLogFile", "LogFile.log", "-ORBDebugLevel", "10");
```
I can see the following errors:
```
(12776|12640) ERROR: Service_Participant::load_configuration import_config () returned -3
(12776|12640) ERROR: Service_Participant::get_domain_participant_factory: load_configuration() failed.
```
That means that, for some reason, the configuration couldn't be `open()`.

I just copy the content of the file, remove it, recreated with the same name and paste the content and worked. I would say that the file has been corrupted somehow during the git push.

Please, let me know if those steps work for you too.

**Comment by ww1965** [comment]
Which configuration are you referring

to?  I saw the same information and return code. The frustrating part for
me is that the HelloWorldPublisher and the HelloWorldSubscriber work. If
you are referring to the rtps.ini file, I played around with by recreating
it and by copying the one from HelloWorldSubscriber.

I pulled the original code as a zip file using the 0.5.0 label from GitHub.

Thanks for looking at it. I’ll give it a try as soon as I hear back from
you regarding which configuration file you are referring to. If it makes
any difference, I’m using a Windows 10 machine.

**Comment by jmmorato** [comment]
Sorry, I meant `rtps.ini` as you guessed. 
All the `.ini` files in the solution you provided seems to have the same issue, are not Windows format and something is failing during the underlying `open()` call needed to read/parse the file.

**Comment by ww1965** [comment]
Thanks. I’ll take a look at them.

**Comment by ww1965** [comment]
I looked at the file in an editor that shows all symbols and there were a
couple of weird characters at the beginning of the file. They don’t show in
a standard editor. Once I removed the odd characters, everything worked
fine. Thanks.

**Comment by mitza-oci** [comment]
> 
> I looked at the file in an editor that shows all symbols and there were a couple of weird characters at the beginning of the file. They don’t show in a standard editor. Once I removed the odd characters, everything worked fine. Thanks.

https://en.wikipedia.org/wiki/Byte_order_mark

**Comment by ww1965** [comment]
Yep. That was it. Seems like the presence of that marking should be handled
on the consuming side but at least I can move forward with using
OpenDDSharp.

**Comment by jmmorato** [comment]
I guess something like `*.ini text` in the `.gitattributes` will fix the future commits after normalization. I'll push and test in the new Hello World repository.

Thanks @mitza-oci for the info.
