### ISSUE TITLE
Error building TestMessage

### ISSUE THREAD

**Issue by Brotbeck** [jmmorato/openddsharp#4]
Upon building project TestMessage, we get the followig error:

Error	C1083	Cannot open include file: 'TestMessageTypeSupportImpl.h': No such file or directory	TestMessage	c:\users\brotbeck\source\repos\openddsharphelloworld\testmessage\testmessagetypesupport.h	15
As a consequnce of this, project HelloWorldPublisher cannot be built.

Could you please give us help.

Kind regards
Marc

**Comment by jmmorato** [comment]
Something went wrong with the native idl project generation. Could you please attach log file that you can find in c:\users\brotbeck\source\repos\openddsharphelloworld\TestMessage\obj\Win32\Debug\obj\Win32\Debug\TestMessageNative.log?

**Comment by Brotbeck** [comment]
Hello
I added the file, but I saw the error with the wrong SDK.  So I installed the SDK version 10.0.16299.0
Now this error is gone and another is coming. I attached a error screen capture to the mail. It seems $(intdir) Is wrong
  The expression "[System.IO.Path]::GetFullPath('')" cannot be evaluated.
Regards Marc

Von: jmorato <notifications@github.com>
Gesendet: Donnerstag, 30. August 2018 15:55
An: jmmorato/openddsharp <openddsharp@noreply.github.com>
Cc: Marc Brotbeck <brotbeck@twi-ag.ch>; Author <author@noreply.github.com>
Betreff: Re: [jmmorato/openddsharp] Error building TestMessage (#4)


Something went wrong with the native idl project generation. Could you please attach log file that you can find in c:\users\brotbeck\source\repos\openddsharphelloworld\TestMessage\obj\Win32\Debug\obj\Win32\Debug\TestMessageNative.log?

**Comment by Brotbeck** [comment]
Helo Jmorato

To delete does solve this Problem, but then I run in another problem, and I could solve this too. At least I could compile and run your “getting started example”.
I recapitulate all the mistake

1.       I installed new Visual Studio 2017 Version 15.8.2

2.       It was then German and I had to install language pack English for better following your sample.
after that in VS 2017  in Tools / Option / International Settings =>  switch to English.

3.       The Win SDK was 10.0.17134.0; I was thinking the newer is okay but it won’t work so I had to install 10.0.16299.0 too and to retarged it
after this I had to delete the Obj Folder in the file explorer of TestMessage

ð  The compilation of TestMessage  is then working

4.       I had then problem to compile the publisher.
first I could not set x86 in the configuration manager. I had to open the HelloWorldSubscirber.csproj and replace the 5 anyCPU with x86.
after reloading in vs the configuration was okay
then I Installed the nugget package, the newest  one , 0.2.0

I had to delete the obj Folder too and then the Compilation was okay but still without any code inserted.

5.       The nugget package does not install the “OpenDDSharp” library to the references of the project. I had to browse it in the solution and add it manually. And I could then use the “using” statement.
                After that the sample was working as expected

                Now I try to use  a DDS wait condition, and for a non c++ developer not easy to do that. ;-)

                Anyway I thank you for your fast care and help.

Regards Marc


Von: jmorato <notifications@github.com>
Gesendet: Donnerstag, 30. August 2018 17:22
An: jmmorato/openddsharp <openddsharp@noreply.github.com>
Cc: Marc Brotbeck <brotbeck@twi-ag.ch>; Author <author@noreply.github.com>
Betreff: Re: [jmmorato/openddsharp] Error building TestMessage (#4)


That's weird and totally new for me.
Try to remove the obj folder and recompile again. If doesn't work please send me the vcxproj that you can find in c:\users\brotbeck\source\repos\openddsharphelloworld\TestMessage\obj\Win32\Debug\TestMessageNative.vcxproj?

**Comment by jmmorato** [comment]
Hi Marc,

Happy to hear you finally compiled. 

About the SDK, yes you are right you must have the 10.0.16299.0, newer ones are not valid. This version defines the minimum Windows OS allowed to run the software. Actually, I'm thinking to use a lower one because 10.0.16299.0 is the one when I started the project but perhaps not the best choice.

About point 4, I guess you started your own projects because in the github example the configurations are already created for x86 and x64 platforms. As explained in #2, you should use the <New...> option of the Configuration Manager to create the new platforms. Anyway, the replacement you did should be ok but perhaps is related with the problem with the missing reference. 

The idea of manually adding the reference is NOT good because when you switch between Debug and Release the dlls are different and could make that the software doesn't work anymore (same between x86 and x64). Perhaps the missing reference is because nuget was not updated correclty. Could you check if your Publisher/Subscriber project file contain the correct nuget version in this lines (at the bottom of the file)?:

`<Import Project="..\packages\OpenDDSharp.0.2.0\build\net461\OpenDDSharp.targets" Condition="Exists('..\packages\OpenDDSharp.0.2.0\build\net461\OpenDDSharp.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\OpenDDSharp.0.2.0\build\net461\OpenDDSharp.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\OpenDDSharp.0.2.0\build\net461\OpenDDSharp.targets'))" />
  </Target>`

**Comment by Brotbeck** [comment]
Von: jmorato <notifications@github.com>
Gesendet: Freitag, 31. August 2018 18:46
An: jmmorato/openddsharp <openddsharp@noreply.github.com>
Cc: Marc Brotbeck <brotbeck@twi-ag.ch>; Author <author@noreply.github.com>
Betreff: Re: [jmmorato/openddsharp] Error building TestMessage (#4)


Hi Marc,

Happy to hear you finally compiled.

About the SDK, yes you are right you must have the 10.0.16299.0, newer ones are not valid. This version defines the minimum Windows OS allowed to run the software. Actually, I'm thinking to use a lower one because 10.0.16299.0 is the one when I started the project but perhaps not the best choice.

About point 4, I guess you started your own projects because in the github example the configurations are already created for x86 and x64 platforms. As explained in #2<https://github.com/jmmorato/openddsharp/issues/2>, you should use the <New...> option of the Configuration Manager to create the new platforms. Anyway, the replacement you did should be ok but perhaps is related with the problem with the missing reference.
==> If I use <New..> the response is: x86 already defined. And otherwise x86 is not available to select.

The idea of manually adding the reference is NOT good because when you switch between Debug and Release the dlls are different and could make that the software doesn't work anymore (same between x86 and x64). Perhaps the missing reference is because nuget was not updated correclty. Could you check if your Publisher/Subscriber project file contain the correct nuget version in this lines (at the bottom of the file)?:

<Import Project="..\packages\OpenDDSharp.0.2.0\build\net461\OpenDDSharp.targets" Condition="Exists('..\packages\OpenDDSharp.0.2.0\build\net461\OpenDDSharp.targets')" /> <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild"> <PropertyGroup> <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them. For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText> </PropertyGroup> <Error Condition="!Exists('..\packages\OpenDDSharp.0.2.0\build\net461\OpenDDSharp.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\OpenDDSharp.0.2.0\build\net461\OpenDDSharp.targets'))" /> </Target>
==> Looks like mine, but for now I play with my demo and learning to use DDS with c#, and this is work enough. With the learning of DDS, I get also experience with this VS 2017 environment.

Regards Marc

**Comment by Brotbeck** [comment]
Hi Morato

My solution ist to large for email
If you give me the email I can enable the dropbox folder for you

Regars Marc

Von: jmorato <notifications@github.com>
Gesendet: Dienstag, 4. September 2018 21:25
An: jmmorato/openddsharp <openddsharp@noreply.github.com>
Cc: Marc Brotbeck <brotbeck@twi-ag.ch>; Author <author@noreply.github.com>
Betreff: Re: [jmmorato/openddsharp] Error building TestMessage (#4)


==> If I use <New..> the response is: x86 already defined. And otherwise x86 is not available to select.

Looks a problem with the project and/or solution file. Just for curiosity, if you zip the your folder and attach it here I'll take a look on it.

==> Looks like mine, but for now I play with my demo and learning to use DDS with c#, and this is work enough. With the learning of DDS, I get also experience with this VS 2017 environment.

That's exactly the reason of this project, learning DDS. So, don't hesitate to ask or report here (better to learn with someone else ;) ).

**Comment by jmmorato** [comment]
Finally, I found some time to dig in your project files configuration. These are the steps I did to fix the issue (changes uploaded to dropbox):

- Removed AnyCPU from the solution file to avoid confusions
- Created the x64 configuration with the configuration manager for Debug and Release
- Fully uninstalled the OpenDDSharp and OpenDDSharp.IdlGenerator nuget packages from the solution
  - You must never install OpenDDSharp nuget in the code generator project, only OpenDDSharp.IdlGenerator
- Removed the manually added references to the OpenDDSharp.dll's
- Installed v0.2.1 in all the projects
- Changed Platform target and output folder for x86 configuration in the project properties of the Publisher and Subscriber (it was configured as AnyCPU)
- Removed bin and obj folder from all projects
- Restored nuget packages
- Rebuild the solution and run the programs

I noticed that sometimes (i.e. when I move the projects from one folder to another or when I remove the packages folder from the solution folder) the OpenDDSharp targets are ignored, therefore the OpenDDSharp dll is not included in the references, just unloading and reloading the publisher and subscriber projects works for me.

**Comment by Brotbeck** [comment]
that works for me
