### ISSUE TITLE
Support Types Not Resolving

### ISSUE THREAD

**Issue by cemrick** [jmmorato/openddsharp#40]
I have been attempting to follow the configuration of the HelloWorld example project per the instructions provided on the website as well as the cope samples included in the master branch of this repository. However, my solution is unable to resolve the reference to a number of types, and I receive the following errors:

1.  The type or namespace name 'MessageTypeSupport' could not be found (are you missing a using directive or an assembly reference?)
2. The type or namespace name 'MessageDataReader' could not be found (are you missing a using directive or an assembly reference?)
3. The type or namespace name 'MessageDataWriter' could not be found (are you missing a using directive or an assembly reference?)

OpenDDSharp Version: 0.5.0 (via NuGet)
Visual Studio Version: 16.9.2
.NET Framework Version: 4.7.2

It seems like these types should be generated from the IdlGenerator project. The "Message" type resolves just fine, and OpenDDSharp.HelloWorld has been imported. Have I missed a configuration step?

**Comment by jmmorato** [comment]
The website documentation was not correctly updated for v0.5.0, try this IDL modification instead:

```
module HelloWorld{
	@topic
	struct Message {
		string Content;
	};
};
```

The full code of the example can be found in: https://github.com/jmmorato/openddsharp_helloworld

**Comment by cemrick** [comment]
That resolved it. Thank you for the prompt response.
