### ISSUE TITLE
Cannot build IDL project - cannot find *TypeSupportImpl.h file

### ISSUE THREAD

**Issue by ww1965** [jmmorato/openddsharp#58]
I am trying to go through the sample exercise and continue to get a build failure that the *TypeSupportImpl.h file cannot be found.  Zip file of the project included - zip file created before building to keep the zip file small.

My steps to recreate
1. installed the latest version of OpenDDSharp IDL Templates 1.7.21124.11
2. Open VS 2019 and create a new OpenDDSharp IDL Project (named it DDSTest and placed it in D:\Temp)
3. added the following to DDSTest.idl
module DDSTest{
	@topic
	struct Message {
		string Content;
	};
};
4. Save
5. Build->Rebuild Solution
6. See the following in the Output tab
Rebuild started...
1>------ Rebuild All started: Project: DDSTest, Configuration: Debug Win32 ------
1>Cleaning DDSTest.idl auto-generated files...
1>Generating native IDL library...
1>Initializing DTE...
1>Generating solution file...
1>Generating project file...
1>Copying IDL files...
1>Building project...
1>Cleaning up resources...
1>Generating DDSTest.idl code...
1>tao-idli_s8YMnj.cpp
1>DDSTestTypeSupport.cpp
1>d:\TEMP\DDSTest\DDSTestTypeSupport.h(12,10): fatal error C1083: Cannot open include file: 'DDSTestTypeSupportImpl.h': No such file or directory
1>.NETFramework,Version=v4.7.2.AssemblyAttributes.cpp
1>Generating Code...
1>Done building project "DDSTest.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
[DDSTest-Initial.zip](https://github.com/jmmorato/openddsharp/files/6510240/DDSTest-Initial.zip)

**Comment by jmmorato** [comment]
Yes, code generation is bugged in last release...

I'm preparing a new release with the fix.

Thanks for reporting.

**Comment by jmmorato** [comment]
Surely tomorrow, perhaps even this afternoon... takes long to build the whole project

**Comment by ww1965** [comment]
Thanks!

**Comment by jmmorato** [comment]
NuGet.org is still validating the new package.... since this morning!

The IDL CodeGeneration package and the VS extension are already listed. You must regenerate the project with the new extension.

**Comment by ww1965** [comment]
Thanks.  Works great now.
