### ISSUE TITLE
Not able to run OpenDDSharp Console App in container image

### ISSUE THREAD

**Issue by senathi123-pip** [jmmorato/openddsharp#61]
Hello,

I have created OpenDDSharp version 0.5.0 Console app which runs fine in my local windows machine.
While I am trying to make container image, it is throwing below exception.

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'OpenDDSharp.dll' or one of its dependencies. The specified module could not be found.
   at DDSharpSub.Program.Main(String[] args)

This is the dockerfile I use to create docker image.

FROM mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019
ARG source
WORKDIR /app
COPY ${source:-obj/Docker/publish} .
ENTRYPOINT ["C:\\app\\Subscriber.exe"]

Can you please help me to resolve this issue?

Regards,
Seetha

**Comment by jmmorato** [comment]
Hi,

That's a common error message when the machine does not accomplish the runtime requirements, mostly because the [VS C++ redistributable](https://aka.ms/vs/16/release/vc_redist.x64.exe) installation.

Is it installed in your docker image? (sorry, no docker installed in my machine right now)

**Comment by senathi123-pip** [comment]
Hello,

Thanks for you reply.

I have tried installing VC++ redistributable and tried to run.
Again it is throwing same error.
I will analyze the container image more.

FROM mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019
ADD https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x64.exe /vc_redist.x64.exe
RUN C:\vc_redist.x64.exe /quiet /install
ARG source
WORKDIR /app
COPY ${source:-obj/Docker/publish} .
ENTRYPOINT ["C:\\app\\Subscriber.exe"]

Regards,
Seetha

**Comment by senathi123-pip** [comment]
Hello,

I have added all the dependencies and it is working fine.
Thanks for you help.

Regards,
Seetha

**Comment by Colborne** [comment]
> 

I am currently having the same error that you had, any additional feedback on how you got this to work?
