### ISSUE TITLE
Release vs Debug builds

### ISSUE THREAD

**Issue by ww1965** [jmmorato/openddsharp#62]
I have a scenario where I build the IDL solution as a separate DLL and then include it in a separate solution (through a nuget package),  The IDL project gets built as Release.  When I build the consuming solution in Debug mode and run it, it fails saying that it cannot load the <idl> module or one of its dependencies.  If I build the consuming solution in Release mode, it runs fine.  I have attached test solutions that illustrate the problem. Any hints or help would be appreciated.
[Test.zip](https://github.com/jmmorato/openddsharp/files/6787350/Test.zip)

**Comment by jmmorato** [comment]
I didn't check your reproducer yet but I would say that is missing the native Release DLLs from the IDL project in the output folder.

OpenDDS is built twice for Release and Debug configuration, the Debug DLLs have the prefix `*d.dll`. The OpenDDSharp NuGet package copies the corresponding DLLs to the output folder using a [targets file](https://github.com/jmmorato/openddsharp/blob/2d9dfcb24e49e829ab397f947d785a7d40aaf808/Sources/OpenDDSharp/OpenDDSharp.targets#L18). You should do something similar in your IDL NuGet package.

Try that and let me know if work for you.

**Comment by ww1965** [comment]
I was able to get all the different builds (x86 and x64 with debug and release) and package those in a nuget package.  Takes some manual editing of the .csproj files when using the nuget (have to manually update the hint path to use $(Platform) instead of x86 or x64, and $(Configuration) instead of debug or release. Here is the section for using OpenDDSharp. Any other nuget that has debug and release and/or x86 and x64 DLLs in the nuget package can use this  pattern.

    <Reference Include="OpenDDSharp, Version=0.7.21141.15, Culture=neutral, processorArchitecture=x86">
      <HintPath>..\packages\OpenDDSharp.0.7.21141.15\lib\net472\$(Platform)\$(Configuration)\OpenDDSharp.dll</HintPath>
    </Reference>
