### ISSUE TITLE
Still memory leak in the Write method when using sequences 

### ISSUE THREAD

**Issue by kuzzh** [jmmorato/openddsharp#64]
The way I use it is almost the same as described in this issue #14 . At the end of this issue, the problem seems to have been solved. However, when I use the latest version of OpenDDSharp (0.7.21141.15), I found that the problem still exists, and memory leaks occur not only at the publisher, but also at the subscriber.

And I also found that sending the sequence was very inefficient and the CPU occupancy is very high, because it uses a byte by byte assignment instead of a whole copy.

Attached you can see my example. I only uploaded the publisher, and it's enough to reproduce the problem.
Thanks!
[Publisher.cs.txt](https://github.com/jmmorato/openddsharp/files/6797025/Publisher.cs.txt)
[SGF_OpenDDS_IDL.idl.txt](https://github.com/jmmorato/openddsharp/files/6797028/SGF_OpenDDS_IDL.idl.txt)
[rtps.ini.txt](https://github.com/jmmorato/openddsharp/files/6797029/rtps.ini.txt)

**Comment by jmmorato** [comment]
I don't think is the same problem than #14 , but I can reproduce the memory leak you noticed.

It seems only happening with unbounded sequences, if you add a bound to the `ByteSeq` typedef the memory looks stable, something like:
`typedef sequence<octet, 2048> ByteSeq;`

I'll investigate if something changed on OpenDDS and implement an explicit release for unbounded sequences.

Thanks for reporting.

**Comment by kuzzh** [comment]
Hi @jmmorato ,

Thanks for your reply. 

I found a post online that says if my key field(that is `serialNum`) changes every time, then a new instance of DDS is created when the write method is called. When I tried filling the `serialNum` with a fixed value, the memory really stabilized. This doesn't feel reasonable and I wonder if there is a way to fix it? Is it possible to have the key field use a different value and still have the memory remain stable?

[ [opendds-main] High Memory Consumption (possible memory leak?)](https://sourceforge.net/p/opendds/mailman/message/36038775/)

**Comment by jmmorato** [comment]
Well... that's the normal behaviour on DDS. Every different key creates a new instance of data, similar to a database if you add new register with the same key the current entry is updated but if you send a different key a new entry is created and the database size is increased.

There are several QoS configuration values that can change the memory footprint, durability, history, reliability,... but by default a datawriter is configured with durability=volatile and should clean up the writer queue as soon the data is send.

I think you actually found a leak, but still need to confirm if it is coming from OpenDDSharp or from OpenDDS. I'm going to try a reproducer using just OpenDDS to isolate the problem.

Unfortunately, I'm leaving for business travels almost all summer and I won't have too much time for the project. I let you know as soon as I find something.

**Comment by kuzzh** [comment]
OK, thanks for your effort!😃

**Comment by jmmorato** [comment]
Fix released in latest version 3.250.2
