### ISSUE TITLE
OpenDDS communication between container and con-container application.

### ISSUE THREAD

**Issue by senathi123-pip** [jmmorato/openddsharp#65]
Hello,

I have created openddsharp desktop application in windows container which will be acting as publisher.
I have subscriber which is written in WPF(C# desktop app) and will be running in another machine.
In this case how can I establish communication between two applications?

I have tried EXPOSE port 8410 in docker image and used SpdpSendAddrs. But it is not working.

Can you please guide me to resolve this issue?

[common]
DCPSGlobalTransportConfig=$file

[domain/42]  
DiscoveryConfig=uni_rtps

[rtps_discovery/uni_rtps]
SedpMulticast=0
ResendPeriod=2
SpdpSendAddrs=172.28.64.1:8410  #subscriber ip 

[transport/the_rtps_transport]
transport_type=rtps_udp
use_multicast=0

Regards,
Seetha

**Comment by jmmorato** [comment]
What kind of networking are you using to run your container? `host` I guess?

I think the best will be to create two different containers, one for the publisher and one for the subscriber, and use `bridge` networking with the default `rtps.ini` file provided in the examples.

**Comment by senathi123-pip** [comment]
Hello,

Thanks for your reply. If both publisher and subscriber are in containers, as you mentioned it is working fine. I have tried that.
Here my subscriber app is WPF app, which can not be added in container. In this case, can you please guide me?

Regards,
Seetha

**Comment by jmmorato** [comment]
Try using `host` networking and default rtps configuration.

> If you use the host network mode for a container, that container’s network stack is not isolated from the Docker host (the 
container shares the host’s networking namespace), and the container does not get its own IP-address allocated. For instance, if you run a container which binds to port 80 and you use host networking, the container’s application is available on port 80 on the host’s IP address.

https://docs.docker.com/network/host/

**Comment by jmmorato** [comment]
Ohh it seems not available for Docker Desktop for Windows... :(

> The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server.

**Comment by senathi123-pip** [comment]
Hello,

Thanks for your reply. How about using RTPSRelay to achieve the communication between container and non container app?

Is OpenDDSharp dll available to use from .NET core or .NET 5.0?

How can I access OpenDDSharp IDL from .NET core or .NET 5.0?

Thanks and Regards,
Seetha

**Comment by jmmorato** [comment]
Hi,

I don't think RTPSRelay could help you. Your issue is that there is not communication at all between the container and the host, that's not an issue related with OpenDDSharp.

Theoretically, you can load  Cpp/Cli assemblies after .NET core 3.1 but I never test it before and perhaps it requires some adjustments to load OpenDDSharp. If you try it, please let me know about the results.

At the end of summer, I plan to release a beta version of OpenDDSharp Standard, then you will have not problem to use it on .NET 5.0 in Windows or Linux.

**Comment by senathi123-pip** [comment]
Hello,

Thanks for your reply. Can you please let me know the progress of OpenDDSharp standard library? Any approximate date in your mind?

Thanks and Regards,
Seetha

**Comment by jmmorato** [comment]
I would start soon to publish beta versions for Windows and Linux, surely end of this month we will have something to test.

**Comment by jmmorato** [comment]
OpenDDSharp has been officially release.

I'm closing this ticket for inactivity but feel free to create new Issues or open new Discussions about the subject.
