### ISSUE TITLE
Could not find RapidJSON Error

### ISSUE THREAD

**Issue by isharrrry** [jmmorato/openddsharp#66]
CL Version is 19.2, architecture is Win32
Visual C++ has C++11 support
Detected Visual C++ version: vs2019
Using ace_src: F:/lib/ACE_wrappers
Using tao_src: F:/lib/ACE_wrappers/TAO
--cmake not specified by user; searching path...
Using CMake 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin/cmake.exe' if needed
Could not find RapidJSON (using 'include/rapidjson/rapidjson.h') in:
    Git Submodule: 'F:/hhl/Lab-V2021-VC142/DDS/openddsharp/ext/OpenDDS/tools/rapidjson'
    Default Install Prefix: 'C:\Program Files (x86)\RapidJSON'
Continuing without it.
ACE_ROOT/ace/config.h exists, skipping configuration of ACE+TAO
ERROR: Requested macro debug not defined for ACE/TAO at configure line 2035.
ERROR: configure failed with errorcode 2
An error occurred when executing task 'SetupThirdParty'.
Error: Error calling the OpenDDS configure script. Exit code: 2
PS F:\hhl\Lab-V2021-VC142\DDS\openddsharp\Build>

**Comment by jmmorato** [comment]
```
Using ace_src: F:/lib/ACE_wrappers
Using tao_src: F:/lib/ACE_wrappers/TAO
```

```
Error: Error calling the OpenDDS configure script. Exit code: 2
PS F:\hhl\Lab-V2021-VC142\DDS\openddsharp\Build
```

I would say you have already another OpenDDS setup in your computer and configured the environment variables `ACE_ROOT`, `TAO_ROOT` and `DDS_ROOT` to that folder. If so, remove the environment variables before calling the OpenDDSharp setup script.

**Comment by jmmorato** [comment]
Closed for inactivity, feel free to reopen it if my previous comment didn't help you
