### ISSUE TITLE
Teamcity Build discrepancy

### ISSUE THREAD

**Issue by PierrePontic** [jmmorato/openddsharp#69]
When building an openDDS project from the developper command line "msbuild -t:Rebuild SSI\ssi.vcxproj -p:Configuration=Debug -p:Platform=Win32", it works fine.

But if the exact same command line is executed by Teamcity, I get the following file not found error : 
'C:\BuildAgent\work\c098bb2b12c25abc\SSI\obj\Win32\Debug\obj\x86\Debug\SSINative.log'

I understand that the task need the SSINative.log file, and it do not exist in the x86 folder, but in the Win32 folder. (as when I build directly from command line)

The teamcity and direct command are executed under the same user name.

Do you have any idea where this discrepancy come from ? what are the conditions to have x86 instead of Win32 in the path ?

`GenerateNativeProjectTarget:
13:36:33
    Generating native IDL library...
13:37:37
  C:\Users\THERACLION\.nuget\packages\openddsharp.idlgenerator\0.5.0\build\OpenDDSharp.IdlGenerator.targets(23,3): error MSB4018: �chec inattendu de la tƒche "GenerateNativeProjectTask". [C:\BuildAgent\work\c098bb2b12c25abc\SSI\ssi.vcxproj]
13:37:37
  C:\Users\THERACLION\.nuget\packages\openddsharp.idlgenerator\0.5.0\build\OpenDDSharp.IdlGenerator.targets(23,3): error MSB4018: System.IO.DirectoryNotFoundException: Impossible de trouver une partie du chemin d'accŠs 'C:\BuildAgent\work\c098bb2b12c25abc\SSI\obj\Win32\Debug\obj\x86\Debug\SSINative.log'. [C:\BuildAgent\work\c098bb2b12c25abc\SSI\ssi.vcxproj]
13:37:37
  C:\Users\THERACLION\.nuget\packages\openddsharp.idlgenerator\0.5.0\build\OpenDDSharp.IdlGenerator.targets(23,3): error MSB4018:    … System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) [C:\BuildAgent\work\c098bb2b12c25abc\SSI\ssi.vcxproj]
13:37:37
  C:\Users\THERACLION\.nuget\packages\openddsharp.idlgenerator\0.5.0\build\OpenDDSharp.IdlGenerator.targets(23,3): error MSB4018:    … System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) [C:\BuildAgent\work\c098bb2b12c25abc\SSI\ssi.vcxproj]
13:37:37
  C:\Users\THERACLION\.nuget\packages\openddsharp.idlgenerator\0.5.0\build\OpenDDSharp.IdlGenerator.targets(23,3): error MSB4018:    … System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) [C:\BuildAgent\work\c098bb2b12c25abc\SSI\ssi.vcxproj]
13:37:37
  C:\Users\THERACLION\.nuget\packages\openddsharp.idlgenerator\0.5.0\build\OpenDDSharp.IdlGenerator.targets(23,3): error MSB4018:    … System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost) [C:\BuildAgent\work\c098bb2b12c25abc\SSI\ssi.vcxproj]
13:37:37
  C:\Users\THERACLION\.nuget\packages\openddsharp.idlgenerator\0.5.0\build\OpenDDSharp.IdlGenerator.targets(23,3): error MSB4018:    … System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost) [C:\BuildAgent\work\c098bb2b12c25abc\SSI\ssi.vcxproj]
13:37:37
  C:\Users\THERACLION\.nuget\packages\openddsharp.idlgenerator\0.5.0\build\OpenDDSharp.IdlGenerator.targets(23,3): error MSB4018:    … OpenDDSharp.BuildTasks.GenerateNativeProjectTask.BuildWithMSBuild() [C:\BuildAgent\work\c098bb2b12c25abc\SSI\ssi.vcxproj]
13:37:37
  C:\Users\THERACLION\.nuget\packages\openddsharp.idlgenerator\0.5.0\build\OpenDDSharp.IdlGenerator.targets(23,3): error MSB4018:    … OpenDDSharp.BuildTasks.GenerateNativeProjectTask.Execute() [C:\BuildAgent\work\c098bb2b12c25abc\SSI\ssi.vcxproj]
13:37:37
  C:\Users\THERACLION\.nuget\packages\openddsharp.idlgenerator\0.5.0\build\OpenDDSharp.IdlGenerator.targets(23,3): error MSB4018:    … Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\BuildAgent\work\c098bb2b12c25abc\SSI\ssi.vcxproj]
13:37:37
  C:\Users\THERACLION\.nuget\packages\openddsharp.idlgenerator\0.5.0\build\OpenDDSharp.IdlGenerator.targets(23,3): error MSB4018:    … Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [C:\BuildAgent\work\c098bb2b12c25abc\SSI\ssi.vcxproj]
13:37:37
  G‚n‚ration du projet "C:\BuildAgent\work\c098bb2b12c25abc\SSI\ssi.vcxproj" termin‚e (Rebuild cible(s)) -- �CHEC.`

**Comment by PierrePontic** [comment]
I forgot to tell : both (teamcity and direct command line) are executed on the same computer.

**Comment by jmmorato** [comment]
The error you are seeing is a bug of v0.5.0 when trying to read the log file after a project build failure, but is not the actual reason when the NativeProject failed to build.

If you have access to the machine, you could check the `SSINative.log` navigating to the corrected path and read the content in order to have more clues about the build project failure.

**Comment by PierrePontic** [comment]
That's a bingo. At the end of SSINative.log : 

'C:\BuildAgent\work\c098bb2b12c25abc\SSI\obj\Win32\Debug\SSINative.vcxproj(620,5): error MSB3073: La commande "cmd /c "\bin\tao_idl -Wb,pre_include=ace/pre.h -Wb,post_include=ace/post.h -I --idl-version 4 --unknown-annotations ignore -Sa -St -I -Wb,export_macro=ColorBoxIDL_Export -Wb,export_include=ColorBoxIDL_Export.h "ColorBox.idl""" s'est arrêtée avec le code 1.'

I guess that the teamcity build agent execute in a different context than the one I use directly...
