### ISSUE TITLE
how to set the QoS policy Durability to PersistentDurabilityQos?

### ISSUE THREAD

**Issue by Brotbeck** [jmmorato/openddsharp#7]
I send a instance of data from a publisher  and I would like to read with a subscriber (messagereader.read)  (not take) periodically this instance of data. but I can only read the data once if the publisher updates the instance. For this i was thinking i have to set the durability QoS to persistentDurabilityQoS. i.e.:

DataReaderQos q = new DataReaderQos();
 
messageReader.GetQos(q);
q.Durability.Kind = DurabilityQosPolicyKind.PersistentDurabilityQos;
ReturnCode x = messageReader.SetQos(q)    

the return code x is ImmutablePolicy
even I try to set the policy by the reader and the writer.
what do I make wrong?

**Comment by jmmorato** [comment]
An immutable property means that once the entity is enabled (datareader, datawriter, participant...) the property cannot be changed. Therefore, you need to set it in the factory creation call:

```
DataReaderQos drQos = new DataReaderQos();
drQos.Durability.Kind = DurabilityQosPolicyKind.PersistentDurabilityQos;
DataReader reader = subscriber.CreateDataReader(topic, drQos);
```
Another option is to configure the factory of the entity (in case of the DataReader the factory is the Subscriber) to don't enable the entity on creation:

```
 SubscriberQos qos = new SubscriberQos();
 qos.EntityFactory.AutoenableCreatedEntities = false;
 Subscriber subscriber = participant.CreateSubscriber(qos);
```
That way, you will need to call messageReader.Enable(); when you finish the configuration of your dataReader.

One clarification about the durability values, in the DDS specification (sorry I mentioned again) is written that to achieve the Transient or Persistence durability the implementation may use an external service. 
I'm not sure if OpenDDS has implemented that kind of durability, perhaps we could ask in the OpenDDS mailing list or @mitza-oci can clarify it here to us.

**Comment by mitza-oci** [comment]
Do you need Durability QoS to meet your requirements?  Durability is about making the writer's data available to readers that were not associated at the time it was written.  That doesn't sound like what you want here.

Instead start with the History QoS policy if you'd like to see more than one update on a specific instance in each `read()`.

While there's bound to be a blurry line between asking questions about the .NET API and asking questions about OpenDDS, if you have questions about how OpenDDS works in general it's probably best to ask in its GitHub project, the mailing list, or even using our commercial services for in-depth architecture, consulting, training, etc.  See http://opendds.org/support.html

**Comment by Brotbeck** [comment]
Thanks to your recommendation, the subscriber can now read the data multiple times.
