### ISSUE TITLE
PersistentDurabilityQos - configuring DCPSPersistentDataDir to specific path doesn't store the data

### ISSUE THREAD

**Issue by Nizzan943** [jmmorato/openddsharp#83]
Hey folks,

I'm trying to enable PersistentDurabilityQos policy.

my writer Qos is:

> dwQos.Durability.Kind = DurabilityQosPolicyKind.PersistentDurabilityQos;
>             dwQos.DurabilityService.HistoryKind = HistoryQosPolicyKind.KeepAllHistoryQos;
>             dwQos.Reliability.Kind = ReliabilityQosPolicyKind.ReliableReliabilityQos;
>             dwQos.ResourceLimits.MaxSamplesPerInstance = 1000;
>             dwQos.History.Kind = HistoryQosPolicyKind.KeepAllHistoryQos;

my topic Qos is: (for both subscriber and publisher)
`topicQos.Durability.Kind = DurabilityQosPolicyKind.PersistentDurabilityQos;`

rtps.ini file: (for both subscriber and publisher)

> [common]
> DCPSGlobalTransportConfig=$file
> DCPSDefaultDiscovery=DEFAULT_RTPS
> DCPSPersistentDataDir=C:\MyGit\openddsharp_helloworld_test2\PersistentData
> DCPSInfoRepo=file://repo.ior
> 
> [transport/the_rtps_transport]
> transport_type=rtps_udp

the app did created new folder at this path but while im running the publisher, the writer writes data but nothing is stored in my folder.

what am I doing wrong?

**Comment by jmmorato** [comment]
I think the persistent durability is not implemented on OpenDDS RTPS, therefore not implemented on OpenDDSharp.

https://github.com/objectcomputing/OpenDDS/blob/c5cb1fc86f68ce4a3fe3b0cc0b510d96c17ef244/docs/design/RTPS#L25

If you have OpenDDS specific questions, better ask in their repo https://github.com/objectcomputing/OpenDDS, I'm sure they will be happy to help.

**Comment by Nizzan943** [comment]
Thanks!
