### ISSUE TITLE
AddPathVC failed due to 2 VC dirs

### ISSUE THREAD

**Issue by Nizzan943** [jmmorato/openddsharp#84]
Hey,

My app recently started to get error:

> The 'AddPathVC' task returned false but did not log an error

I've investigated it and the issue is ExecuteVSWhereCommand return 2 paths and merge them together.
I had 2 VCs in C:\Program Files(x86)\Microsoft Visual Studio\2019.

-  C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
-  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools

 because off:
https://github.com/jmmorato/openddsharp/blob/c0838e4fb95f21eba0051ec92f758a9e6b9157a6/Sources/OpenDDSharp.BuildTasks/AddPathVC.cs#L62 Line is removing \r\n.

install logs:
> AddPathVCTarget:
         Add Visual C++ to the PATH...
         Adding VC to the PATH...
         Platform: x64
         VC Install Path: C:\Program Files (x86)\Microsoft Visual Studio\2019\ProfessionalC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    14>C:\Git\openddsharp\Tests\TestIdlStandard\TestIdlStandard.csproj(68,5): error : Microsoft.VCToolsVersion.default.txt not found: C:\Program Files (x86)\Microsoft Visual Studio\2019\ProfessionalC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.txt

The solution is to check if 2 paths returned, split them and take only 1 of the paths, or else remove on of the VC dirs.
In my case I have removed BuildTools and kept the Professionals.

**Comment by jmmorato** [comment]
Thanks for reporting.

I will fix for next version or... feel free to pull request your changes ;)

**Comment by jmmorato** [comment]
Fixed in version 0.8.22111.86-beta. Fill free to reopen if you found an error.
