### ISSUE TITLE
C# IDL generator generates empty files

### ISSUE THREAD

**Issue by RomanKapl** [jmmorato/openddsharp#89]
Hi,
I'm trying to create TypeSupport C# files by using the IDL generator package,
the IDL contains the following structures-

```
module PingPong{

	@topic
	struct Ping {
		long TimeStamp;
	};

	@topic
	struct Pong {
		long TimeStamp;
	};
}; 
```
in the end, I can't see any content inside the generated file,

I'm using the following packages versions for .net standard 2.0- 
OpenDDSharp.Standard Version 0.8.21289.1-beta
OpenDDSharp.Standard.IdlGenerator Version= 0.8.21289.1-beta

it empty, any clue how to overcome this issue?

Thanks in advance :)

**Comment by jmmorato** [comment]
Did you create the project with the template?

https://github.com/jmmorato/openddsharp/blob/develop/Documentation/OpenDDSharp.Standard.Doc/articles/getting_started.md#install-the-openddsharp-templates

**Comment by RomanKapl** [comment]
Hi,
 
Thanks for the quick response, seems like this specific file is behaves in a weird way (might be text encoding?)
created manually in a new file and work perfectly, the old one still doesn't work.

Roman
