### ISSUE TITLE
Serializing DDS messages

### ISSUE THREAD

**Issue by ww1965** [jmmorato/openddsharp#96]
Is there support for serializing the DDS messages to a byte array that can be captured without actually sending the message?  It looks like OpenDDS supports this via CDR but I don't see any exposed way to do this in OpenDDSharp.

Thanks.

**Comment by ww1965** [comment]
Not sure if other users would be interested, but I would get a lot of value out of having the serialization available and could make use of it immediately.

**Comment by jmmorato** [comment]
What exactly OpenDDS API do you need?
What version of OpenDDSharp are you using?

For your information. the Cpp/Cli wrapper is frozen and I'm not going to release new version, if you are working with the standard wrapper, I could try to  integrate it in future versions

**Comment by jmmorato** [comment]
Closed for inactivity.
Feel free to reopen or create a new ticket with the requested API.
