### ISSUE TITLE
"map" support in IDL

### ISSUE THREAD

**Issue by JonathanWheelerL3** [jmmorato/openddsharp#97]
It looks like the IDL specification from 1.3 onward supports the map type via

typedef map<T,V> M1;

But when I try to add this into an IDL and compile it with the extension, I get this error
`1>Error - C:\Users\Jonathan.Wheeler\.nuget\packages\openddsharp.idlgenerator\0.7.21141.15\build\..\tools\openddsharp_idl.exe: "Chat.idl", line 4: error in lookup of symbol: map`

For reference, my test IDL is the following:

```
module Chat{
	typedef sequence<long> LongList;
	typedef sequence<string> StringList;
	typedef map<long, string> M1;

	@topic
	struct Message {
		string Content;
		LongList Numbers;
	};

	@topic
	struct DeleteMessageCommand {
		long Id;
		string Source;
	};
};
```

**Comment by JonathanWheelerL3** [comment]
Unless I'm mistaken, I've stumbled upon where the problem actually is. Another user reported being unable to use some other IDL specifications here on OpenDDS: https://github.com/objectcomputing/OpenDDS/issues/1275

The answer is that TAO is the problem here and doesn't support these specifications. I am trying to track down more information about TAO choosing to not support things from IDL 4, but it's a quagmire of information. If you have any ideas, I'd love some pointers; but at this point I feel confident this isn't an issue with your code, but further up in the dependency list.

**Comment by jmmorato** [comment]
I can ensure you that the mapping is not implemented in OpenDDSharp and I'm pretty sure neither in OpenDDS. Even more, I don't know any other DDS implementation that implement that mapping.
